### ISSUE TITLE
知乎上有人用这个repo的图片来给自己的公众号吸引粉丝

### ISSUE THREAD

**Issue by satoi8080** [TeamStuQ/skill-map#105]
https://zhuanlan.zhihu.com/p/28781950
戳进去下载地址之后解压密码关注公众号才能拿到
不举报吗？

**Comment by lmdeditor** [comment]
感谢提醒，未经授权而且不标明原创出处，是可以举报的。

**Comment by ShumiXu** [comment]
您好，我是许玉双，您的邮件我已收到，谢谢

**Comment by cnaohexin** [comment]
我已收到，将尽快回复您。如事情紧急，请直接拨打电话13552697681.多谢
